@echo off
echo [Support Intel] Initializing Local Repository...
git init
echo [Support Intel] Adding files...
git add .
echo [Support Intel] Committing...
git commit -m "Initial commit of Support Intel Dashboard"
echo [Support Intel] Linking to GitHub...
git remote add origin https://github.com/chinmayv-bob/Support-Intel-Dashboard.git
git branch -M main
echo [Support Intel] Pushing to GitHub (this may ask for your login)...
git push -u origin main
echo [Support Intel] Done! Your code is now on GitHub.
pause
