import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { useTrends } from '../hooks/useTrends';
import { useDashboard } from '../hooks/useDashboard';
import { Skeleton } from '../components/shared/Skeleton';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

const HandoffView: React.FC = () => {
    const { data: trendsData, isLoading: isTrendsLoading } = useTrends();
    const { data: dashboard, isLoading: isDashboardLoading } = useDashboard();
    const [activeIndex, setActiveIndex] = useState(0);
    const [isCopied, setIsCopied] = useState(false);

    const isLoading = isTrendsLoading || isDashboardLoading;

    // Filter trends that need engineering escalation
    const escalations = useMemo(() => {
        return (trendsData?.trends || []).filter(t => t.needs_escalation);
    }, [trendsData]);

    // Guard: clamp activeIndex if escalations shrink
    const safeIndex = activeIndex >= escalations.length ? 0 : activeIndex;
    const currentTrend = escalations[safeIndex];

    // Match ticket_ids from the current trend to critical tickets for detail
    const affectedTickets = useMemo(() => {
        if (!currentTrend || !dashboard?.criticalTickets) return [];
        const trendTicketIds = currentTrend.ticket_ids || [];
        return dashboard.criticalTickets.filter(t =>
            trendTicketIds.some(id => String(t.ticket_id).includes(id) || String(id).includes(t.ticket_id))
        );
    }, [currentTrend, dashboard]);

    // Generate Jira/Slack handoff block from trend data
    const generateJiraBlock = () => {
        if (!currentTrend) return '';
        const ticketIds = currentTrend.ticket_ids || [];
        const severity = currentTrend.state === 'ESCALATING' ? 'High (P1)' : currentTrend.state === 'NEW' ? 'Medium (P2)' : 'Low (P3)';

        return [
            `**Defect Summary**: ${currentTrend.title}`,
            `**Trend ID**: ${currentTrend.trend_id}`,
            `**Severity**: ${severity}`,
            `**State**: ${currentTrend.state}`,
            `**Impact**: ${ticketIds.length} Affected Tickets`,
            `**RCA**: ${currentTrend.root_cause}`,
            `**Confidence**: ${currentTrend.confidence}%`,
            `**Growth**: ${currentTrend.growth_percentage}%`,
            `**First Seen**: ${currentTrend.first_seen}`,
            `**Last Seen**: ${currentTrend.last_seen}`,
            ``,
            `**Affected Tickets**:`,
            ...ticketIds.map(id => `- ${id}`),
            ``,
            `**Action Required**:`,
            `Engineering investigation required for root cause resolution.`,
            ``,
            `Generated by Support Intel AI • ${new Date().toISOString().split('T')[0]}`
        ].join('\n');
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generateJiraBlock());
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
    };

    // ── LOADING STATE ──
    if (isLoading) {
        return (
            <div className="space-y-6 pb-12">
                <Skeleton className="h-10 w-72" />
                <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
                    <div className="xl:col-span-2 space-y-6">
                        <Skeleton className="h-64 w-full rounded-xl" />
                        <Skeleton className="h-48 w-full rounded-xl" />
                    </div>
                    <Skeleton className="h-96 w-full rounded-xl" />
                </div>
            </div>
        );
    }

    // ── EMPTY STATE ──
    if (escalations.length === 0) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
                <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    transition={{ duration: 0.4, ease: 'easeOut' }}
                >
                    <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-emerald-100 mb-6">
                        <span className="material-symbols-outlined text-emerald-600 text-[40px]">check</span>
                    </div>
                    <h2 className="text-2xl font-bold text-slate-900 mb-2">No Active Escalations</h2>
                    <p className="text-slate-500 max-w-md mx-auto mb-8">
                        All systems are operating within normal parameters. No trends currently require engineering intervention.
                    </p>
                    <div className="text-xs text-slate-400 font-mono border-t border-slate-200 pt-4 inline-block px-8">
                        Last checked: {dashboard?.generatedAt || '—'}
                    </div>
                </motion.div>
            </div>
        );
    }

    // ── ACTIVE STATE ──
    return (
        <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: 'easeOut' }}
            className="space-y-6 pb-12"
        >
            {/* Tab Switcher for multiple escalations */}
            <header className="flex items-center justify-between">
                <div className="flex items-center gap-2 overflow-x-auto pb-1">
                    {escalations.map((esc, i) => (
                        <button
                            key={esc.trend_id}
                            onClick={() => { setActiveIndex(i); setIsCopied(false); }}
                            className={cn(
                                "px-4 py-2 rounded-lg text-xs font-bold whitespace-nowrap transition-all border",
                                i === activeIndex
                                    ? "bg-slate-900 text-white border-slate-900 shadow-md"
                                    : "bg-white text-slate-500 border-slate-200 hover:bg-slate-50 hover:border-slate-300"
                            )}
                        >
                            <span className={cn(
                                "inline-block size-2 rounded-full mr-2",
                                esc.state === 'ESCALATING' ? "bg-red-500 animate-pulse" : "bg-amber-500"
                            )} />
                            {esc.title}
                        </button>
                    ))}
                </div>
                <div className="flex items-center gap-3 text-xs text-slate-400 shrink-0">
                    <span className="font-mono">Last updated: {dashboard?.generatedAt || '—'}</span>
                </div>
            </header>

            {/* Main Content Grid */}
            <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
                {/* Left Column: 2/3 */}
                <div className="xl:col-span-2 flex flex-col gap-6">

                    {/* Header Card */}
                    <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
                        <div className="space-y-2">
                            <div className="flex items-center gap-3">
                                <h1 className="text-2xl font-bold text-slate-900 leading-tight">{currentTrend.title}</h1>
                                <span className={cn(
                                    "px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wide border",
                                    currentTrend.state === 'ESCALATING'
                                        ? "bg-red-100 text-red-700 border-red-200"
                                        : currentTrend.state === 'NEW'
                                            ? "bg-blue-100 text-blue-700 border-blue-200"
                                            : "bg-amber-100 text-amber-700 border-amber-200"
                                )}>
                                    {currentTrend.state}
                                </span>
                            </div>
                            <div className="flex items-center gap-3 text-sm text-slate-500">
                                <span className="font-mono bg-slate-100 px-1.5 py-0.5 rounded text-xs text-slate-600">{currentTrend.trend_id}</span>
                                <span>•</span>
                                <span>{(currentTrend.ticket_ids || []).length} affected tickets</span>
                                <span>•</span>
                                <span>Detected {currentTrend.first_seen}</span>
                            </div>
                        </div>
                        <div className="flex items-center gap-3">
                            <button
                                onClick={handleCopy}
                                className={cn(
                                    "flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-all shadow-sm active:scale-95",
                                    isCopied ? "bg-emerald-500 text-white" : "bg-slate-900 text-white hover:bg-black"
                                )}
                            >
                                <AnimatePresence mode="wait">
                                    {isCopied ? (
                                        <motion.div key="copied" initial={{ y: 10, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: -10, opacity: 0 }} className="flex items-center gap-2">
                                            <span className="material-symbols-outlined text-[16px]">check_circle</span>
                                            <span>Copied!</span>
                                        </motion.div>
                                    ) : (
                                        <motion.div key="copy" initial={{ y: 10, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: -10, opacity: 0 }} className="flex items-center gap-2">
                                            <span className="material-symbols-outlined text-[16px]">content_copy</span>
                                            <span>Copy for Jira</span>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </button>
                        </div>
                    </div>

                    {/* AI Root Cause Analysis */}
                    <section className="rounded-xl overflow-hidden border border-slate-200 bg-white shadow-sm">
                        <div className="bg-gradient-to-r from-indigo-50/50 to-white p-5 border-b border-slate-100 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="size-8 rounded bg-indigo-100 text-indigo-600 flex items-center justify-center ring-1 ring-indigo-200">
                                    <span className="material-symbols-outlined text-[20px]">auto_awesome</span>
                                </div>
                                <h2 className="text-slate-900 text-base font-bold">AI Root Cause Analysis</h2>
                            </div>
                            <div className="flex items-center gap-3">
                                <div className="text-right">
                                    <p className="text-[10px] uppercase text-slate-500 font-bold tracking-wider">Confidence</p>
                                    <p className={cn(
                                        "text-sm font-bold",
                                        currentTrend.confidence >= 80 ? "text-emerald-600" :
                                            currentTrend.confidence >= 50 ? "text-amber-600" : "text-red-600"
                                    )}>{currentTrend.confidence}%</p>
                                </div>
                                <div className={cn(
                                    "h-8 w-8 rounded-full border-2 flex items-center justify-center",
                                    currentTrend.confidence >= 80 ? "border-emerald-500" :
                                        currentTrend.confidence >= 50 ? "border-amber-500" : "border-red-500"
                                )}>
                                    <span className={cn(
                                        "block w-2 h-2 rounded-full",
                                        currentTrend.confidence >= 80 ? "bg-emerald-500" :
                                            currentTrend.confidence >= 50 ? "bg-amber-500" : "bg-red-500"
                                    )} />
                                </div>
                            </div>
                        </div>
                        <div className="p-6 space-y-4">
                            <div>
                                <div className="flex items-center gap-2 mb-2">
                                    <span className="material-symbols-outlined text-slate-400 text-sm">psychology</span>
                                    <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Probable Cause</p>
                                </div>
                                <p className="text-slate-900 text-base leading-relaxed">
                                    {currentTrend.root_cause}
                                </p>
                            </div>
                            <div className="grid grid-cols-2 gap-4 pt-4 border-t border-slate-100">
                                <div className="bg-slate-50 rounded-lg p-3">
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Growth Rate</p>
                                    <p className="text-lg font-black text-slate-900">{currentTrend.growth_percentage}%</p>
                                </div>
                                <div className="bg-slate-50 rounded-lg p-3">
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Ticket Count</p>
                                    <p className="text-lg font-black text-slate-900">{currentTrend.ticket_count || (currentTrend.ticket_ids || []).length}</p>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* Jira / Slack Handoff Block */}
                    <section className="flex flex-col rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
                        <div className="px-5 py-3 border-b border-slate-200 flex justify-between items-center bg-slate-50">
                            <div className="flex items-center gap-3">
                                <span className="material-symbols-outlined text-slate-400 text-[20px]">terminal</span>
                                <h3 className="text-slate-900 text-sm font-bold font-mono tracking-tight">JIRA / SLACK HANDOFF</h3>
                            </div>
                        </div>
                        <div className="p-0 bg-[#0d1117] relative group">
                            <div className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                                <span className="text-[9px] uppercase font-bold tracking-wider text-slate-500 bg-slate-800/80 px-1.5 py-0.5 rounded border border-slate-700">Markdown</span>
                            </div>
                            <pre className="text-slate-300 p-6 overflow-x-auto text-xs font-mono leading-relaxed selection:bg-primary/30 whitespace-pre-wrap">
                                {generateJiraBlock()}
                            </pre>
                        </div>
                    </section>

                </div>

                {/* Right Column: 1/3 */}
                <div className="xl:col-span-1 flex flex-col gap-6">

                    {/* Anomaly Detection — Coming Soon */}
                    <div className="bg-slate-50 rounded-xl border border-dashed border-slate-300 p-6 flex flex-col items-center justify-center text-center h-48 relative overflow-hidden group">
                        <div className="absolute inset-0 bg-white/40 backdrop-blur-[1px] z-10 flex flex-col items-center justify-center">
                            <span className="bg-slate-200 text-slate-600 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider mb-2 shadow-sm">Coming Soon</span>
                            <p className="text-sm font-medium text-slate-500">Anomaly Detection: Latency</p>
                        </div>
                        <div className="w-full h-full opacity-20 blur-sm pointer-events-none flex items-end gap-1">
                            <div className="bg-slate-400 w-1/6 h-[30%]" />
                            <div className="bg-slate-400 w-1/6 h-[50%]" />
                            <div className="bg-slate-400 w-1/6 h-[40%]" />
                            <div className="bg-red-400 w-1/6 h-[90%]" />
                            <div className="bg-slate-400 w-1/6 h-[60%]" />
                            <div className="bg-slate-400 w-1/6 h-[45%]" />
                        </div>
                    </div>

                    {/* Affected Tickets */}
                    <div className="bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col flex-1 min-h-[400px]">
                        <div className="px-5 py-4 border-b border-slate-200 flex justify-between items-center">
                            <h3 className="text-slate-900 text-sm font-bold">Affected Tickets</h3>
                            <span className="bg-slate-100 text-slate-700 px-2 py-0.5 rounded text-xs font-semibold">
                                {(currentTrend.ticket_ids || []).length} Total
                            </span>
                        </div>
                        <div className="flex-1 overflow-y-auto p-2 space-y-1">
                            {affectedTickets.length > 0 ? (
                                affectedTickets.map((ticket, i) => (
                                    <div key={i} className="p-3 rounded-lg hover:bg-slate-50 cursor-pointer border border-transparent hover:border-slate-200 transition-all group">
                                        <div className="flex justify-between items-start mb-1">
                                            <span className="text-indigo-600 font-mono text-[11px] font-semibold bg-indigo-50 px-1.5 rounded">{ticket.ticket_id}</span>
                                            <span className="text-slate-400 text-[10px]">{ticket.aging}</span>
                                        </div>
                                        <p className="text-slate-900 text-sm font-medium line-clamp-1 group-hover:text-primary transition-colors mt-1">{ticket.summary}</p>
                                        <div className="flex items-center gap-2 mt-2">
                                            <span className={cn(
                                                "text-[10px] font-bold px-1.5 py-0.5 rounded",
                                                (ticket.sentiment?.score || 10) <= 3
                                                    ? "bg-red-50 text-red-600"
                                                    : "bg-slate-50 text-slate-500"
                                            )}>
                                                Sentiment: {ticket.sentiment?.score || '—'}
                                            </span>
                                            <span className="text-slate-400 text-[10px]">•</span>
                                            <span className="text-slate-500 text-xs">{ticket.panel}</span>
                                        </div>
                                    </div>
                                ))
                            ) : (
                                // Show ticket IDs when no detail match found
                                (currentTrend.ticket_ids || []).map((id, i) => (
                                    <div key={i} className="p-3 rounded-lg hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-all">
                                        <span className="text-indigo-600 font-mono text-[11px] font-semibold bg-indigo-50 px-1.5 rounded">{id}</span>
                                    </div>
                                ))
                            )}
                        </div>
                        {(currentTrend.ticket_ids || []).length > affectedTickets.length && affectedTickets.length > 0 && (
                            <div className="p-3 border-t border-slate-200">
                                <p className="text-center text-xs text-slate-400">
                                    {(currentTrend.ticket_ids || []).length - affectedTickets.length} additional tickets not in current view
                                </p>
                            </div>
                        )}
                    </div>

                </div>
            </div>
        </motion.div>
    );
};

export default HandoffView;
