import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

const HandoffView: React.FC = () => {
    const [isCopied, setIsCopied] = useState(false);

    const handoffContent = `[INCIDENT] High Latency detected in Payment Gateway (EU Cluster)
---------------------------------------------------------------
SEVERITY:    P1 - Critical
IMPACT:      ~15% of EU traffic experiencing >5s latency
COMPONENT:   Billing Service / Stripe Wrapper
---------------------------------------------------------------
AI ANALYSIS:
Probable Root Cause: Database locking on users_primary table during batch operations.
Confidence: 96.4%
TECHNICAL EVIDENCE:
1. Log Signal: 524 Timeout errors starting at 14:00 UTC
2. Correlation: Spikes align with cron job cron_billing_eu
3. Sample Trace: req_88f921_beta (See attached logs)
RECOMMENDED ACTION:
- Restart billing-worker-04
- Investigate deadlock on users_primary index
- Rollback recent deployment #4492 if restart fails
Generated by Support Intel AI • 2026-02-05`;

    const handleCopy = () => {
        navigator.clipboard.writeText(handoffContent);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
    };

    return (
        <div className="space-y-8 pb-12">
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
                <div>
                    <div className="flex items-center gap-3 mb-2">
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 text-slate-600 border border-slate-200 uppercase tracking-wide">Ticket #8821-A</span>
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700 border border-red-200 uppercase tracking-wide">Critical</span>
                    </div>
                    <h1 className="text-3xl font-black text-slate-900 leading-tight">Trend Analysis & Handoff</h1>
                </div>
                <div className="flex items-center gap-3 text-slate-500 text-sm font-medium">
                    <span className="flex items-center gap-1.5"><span className="size-2 bg-emerald-500 rounded-full animate-pulse"></span> Analysis Complete</span>
                    <span className="text-slate-300">|</span>
                    <span>Generated 2m ago</span>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Anomaly Detection Card */}
                <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 flex flex-col h-full relative overflow-hidden group">
                    <div className="absolute right-0 top-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
                        <span className="material-symbols-outlined text-9xl text-slate-900">psychology_alt</span>
                    </div>
                    <div className="flex items-center gap-3 mb-4 relative z-10">
                        <div className="p-2 bg-indigo-50 rounded-lg border border-indigo-100">
                            <span className="material-symbols-outlined text-primary">psychology_alt</span>
                        </div>
                        <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">AI Probable Cause</span>
                    </div>
                    <div className="relative z-10">
                        <h3 className="text-2xl font-bold text-slate-900 mb-2">Upstream Timeout (Gateway)</h3>
                        <p className="text-sm text-slate-600 leading-relaxed italic">
                            Pattern matches CloudFlare 524 errors correlated with batch-processing job cron_billing_eu.
                        </p>
                    </div>
                </div>

                {/* Confidence Card */}
                <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 flex flex-col h-full relative overflow-hidden group">
                    <div className="flex items-start justify-between mb-4 relative z-10">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-emerald-50 rounded-lg border border-emerald-100 text-emerald-600">
                                <span className="material-symbols-outlined">verified</span>
                            </div>
                            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Confidence Score</span>
                        </div>
                        <span className="bg-emerald-100 text-emerald-700 text-[10px] font-bold px-2 py-0.5 rounded-full uppercase">High Certainty</span>
                    </div>
                    <div className="relative z-10 px-2 mt-auto pb-4">
                        <div className="flex items-baseline gap-3 mb-2">
                            <p className="text-4xl font-black text-slate-900">96.4%</p>
                            <span className="text-sm font-medium text-slate-400">Match Accuracy</span>
                        </div>
                        <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden">
                            <motion.div
                                initial={{ width: 0 }}
                                animate={{ width: "96.4%" }}
                                transition={{ duration: 1, ease: "easeOut" }}
                                className="bg-emerald-500 h-full rounded-full"
                            />
                        </div>
                    </div>
                </div>
            </div>

            {/* Latency Anomaly Chart Section */}
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 flex flex-col">
                <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
                    <div>
                        <h3 className="text-lg font-bold text-slate-900">Anomaly Detection: Latency</h3>
                        <p className="text-sm text-slate-500">30-day signal analysis with AI thresholding</p>
                    </div>
                    <div className="flex items-center gap-4">
                        <div className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-slate-400"></span><span className="text-xs font-medium text-slate-500">Baseline</span></div>
                        <div className="flex items-center gap-1.5"><span className="size-2 rounded-full bg-red-500 animate-pulse"></span><span className="text-xs font-bold text-slate-900">Anomaly</span></div>
                    </div>
                </div>
                <div className="relative h-48 w-full">
                    <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 478 150">
                        <path d="M0 130 L 50 128 L 100 132 L 150 129 L 200 131 L 250 128 L 300 130 L 350 129" fill="none" stroke="#94a3b8" strokeWidth="2" opacity="0.3" markerEnd="url(#dot)" />
                        <motion.path
                            initial={{ pathLength: 0 }}
                            animate={{ pathLength: 1 }}
                            transition={{ duration: 1.5, ease: "easeInOut" }}
                            d="M350 129 L 380 40 L 410 20 L 440 35 L 478 25"
                            fill="none"
                            stroke="#ef4444"
                            strokeWidth="4"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                        />
                        <circle cx="410" cy="20" r="5" fill="#fff" stroke="#ef4444" strokeWidth="3" />
                    </svg>
                </div>
            </div>

            {/* Engineering Handoff Artifact Card */}
            <div className="bg-white rounded-xl border border-slate-200 shadow-lg overflow-hidden flex flex-col">
                <div className="px-6 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="size-8 rounded bg-slate-200 flex items-center justify-center">
                            <span className="material-symbols-outlined text-slate-500 text-[18px]">terminal</span>
                        </div>
                        <div>
                            <h3 className="text-sm font-bold text-slate-900">Engineering Handoff Artifact</h3>
                            <p className="text-xs text-slate-500">Formatted for Jira/Slack Issue Tracking</p>
                        </div>
                    </div>

                    <button
                        onClick={handleCopy}
                        className={cn(
                            "relative flex items-center gap-2 px-6 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wide transition-all shadow-sm overflow-hidden min-w-[140px] justify-center",
                            isCopied ? "bg-emerald-500 text-white" : "bg-slate-900 text-white hover:bg-slate-800"
                        )}
                    >
                        <AnimatePresence mode="wait">
                            {isCopied ? (
                                <motion.div
                                    key="copied"
                                    initial={{ y: 20, opacity: 0 }}
                                    animate={{ y: 0, opacity: 1 }}
                                    exit={{ y: -20, opacity: 0 }}
                                    className="flex items-center gap-2"
                                >
                                    <span className="material-symbols-outlined text-[16px]">check_circle</span>
                                    <span>Copied!</span>
                                </motion.div>
                            ) : (
                                <motion.div
                                    key="copy"
                                    initial={{ y: 20, opacity: 0 }}
                                    animate={{ y: 0, opacity: 1 }}
                                    exit={{ y: -20, opacity: 0 }}
                                    className="flex items-center gap-2"
                                >
                                    <span className="material-symbols-outlined text-[16px]">content_copy</span>
                                    <span>Copy for Jira</span>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </button>
                </div>
                <div className="p-0 bg-slate-900 overflow-x-auto">
                    <pre className="font-mono text-xs leading-relaxed p-8 text-slate-300 whitespace-pre selection:bg-primary/30">
                        {handoffContent}
                    </pre>
                </div>
            </div>
        </div>
    );
};

export default HandoffView;
